### ISSUE TITLE
INVENTORY: Cant pick up items from ground wich have been dropped!

### ISSUE THREAD

**Issue by drazoxXD** [Mercy-Collective/mercy-framework#14]
No errors just cant pick up items!
![image](https://github.com/Mercy-Collective/mercy-framework/assets/68930610/75666832-1aa3-41a7-8806-87d36fbd2903)

**Comment by drazoxXD** [comment]
I have posted on Discord too!

**Comment by Savage912-Official** [comment]
> No errors just cant pick up items!
> ![image](https://user-images.githubusercontent.com/68930610/241653769-75666832-1aa3-41a7-8806-87d36fbd2903.png)

No f8 errors or console error?

**Comment by BlackZon77** [comment]
> No errors just cant pick up items! ![image](https://user-images.githubusercontent.com/68930610/241653769-75666832-1aa3-41a7-8806-87d36fbd2903.png)

I was having the same problem, where i can drop one or multiple items but when i try to pick them up it stays the same as the image giving no error in f8 or console.

**Comment by Savage912-Official** [comment]
Hmm I’ll take a look tomorrow when I’m back on my pc.

**Comment by AwayFromKane** [comment]
Just pushed fix.

**Comment by AwayFromKane** [comment]
Issue should be resolved in latest push.

**Comment by drazoxXD** [comment]
@AwayFromKane Check my comment on the commit!
