### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by PuzzleTV** [Mercy-Collective/mercy-framework#15]
Hi, I downloaded Mercy-Framework since 4 days now and I can see some problem:

1. On Character Creation, Skin model don't save in sql since new commits. (https://i.imgur.com/Fw2aBPN.png) - **FIXED**

2. House Cleaning and Dark Market Transports NPC's don't spawn. (https://i.imgur.com/FhxSSD6.jpeg)

3. When you hire someone in your business created by the judge, the business don't appear in other guy phone 
(My POV: https://i.imgur.com/xrxWqFu.png
Other dude POV: https://i.imgur.com/CvKs6lI.png)

4. I hosted the casino wheel and it don't work (in my browser and in-game)
(My Browser: https://i.imgur.com/sQ1TK8K.png
In-Game: https://i.imgur.com/xuyOs75.png)

5. On present opening, It duplicates items like 3 phones idk if it's random (https://i.imgur.com/u6WzqPj.png) - **FIXED**

6. When Dropping something on the ground, the ground inventory cannot be reopened
(Before: https://i.imgur.com/7HWq2a0.jpeg
After: https://i.imgur.com/xy0FV3s.jpeg)

7. When you put some items in a stash, it only show one item by one (https://i.imgur.com/KdsdJRD.jpeg)

**Comment by BlackZon77** [comment]
I think the first problem about skin model is fixed in the last commit but didnt try it on character creation

**Comment by AwayFromKane** [comment]
2 and 6 should be fixed in latest push, not sure about 7. 
3. Might just be a syncing issue I think.
4. If you are hosting the casino wheel the link should look something like http://localhost:3000/WHEELFOLDERNAME
Also the wheel enables itself when walking through the casino doors.

If there is anything else, I am here to help.
